# anything with wildcards needs quotes since wildcards might contain characters
# that are openly hostile to most shells
cluster:
  mkdir -p cluster_logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-'{rule}-{wildcards}'
    --output='cluster_logs/{rule}/%j-{wildcards}.out'
    --time={resources.time}
default-resources:
  - partition=batch
  - mem_mb=4000
  - time="8:0:0"
set-resources:
  - label_vcf:mem_mb=32000
  - sort_and_filter_simple_repeats:mem_mb=16000
  - get_homopolymers:mem_mb=16000
  - annotate_labeled_variants:mem_mb=32000
  - annotate_unlabeled_variants:mem_mb=32000
  - summarize_labeled_annotated_variants:mem_mb=32000
  - summarize_unlabeled_annotated_variants:mem_mb=32000
  - summarize_labeled_output:mem_mb=16000
  - summarize_unlabeled_output:mem_mb=16000
  - prepare_train_data:mem_mb=96000
  - prepare_labeled_test_data:mem_mb=32000
  - prepare_unlabeled_test_data:mem_mb=32000
  - summarize_model:mem_mb=32000
  - train_model:mem_mb=32000
  - decompose_model:mem_mb=32000
set-threads:
  - train_ebm=4
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-cancel: "scancel"
