stages:
  snakemake:
    cmd: snakemake --configfile=config/config.yml --profile workflow/profiles/nisaba
    deps:
    - config/config.yml
    outs:
    - results/annotated_variants:
        persist: true
    - results/log:
        persist: true
    - results/model:
        persist: true
