vars:
  - config/dvc-params.yml

stages:
  snakemake:
    cmd: snakemake --configfile=config/${config} --profile workflow/profiles/${profile}
    deps:
    - config/${config}
    outs:
    - results/annotated_input:
        persist: true
    - results/log:
        persist: true
    - results/ebm:
        persist: true
