reference_sets:
  GRCh38_XY:
    ref: GRCh38
    chr_filter: [23, 24]

labeled_queries:
  HG002_Element_DV:
    refset: GRCh38_XY
    chr_prefix: chr
    src:
      url: https://storage.googleapis.com/brain-genomics/awcarroll/share/giab/element/HG002.element_dfrac_0.616.grch38.vcf.gz
    benchmark: HG002_asm_v27_XY
    variables:
      coverage: 50
      seqtech: Element
      variant_caller: DeepVariant
    corrections:
      fix_refcall_gt: true

  HG002_Illumina_DV:
    refset: GRCh38_XY
    chr_prefix: chr
    src:
      url: https://storage.googleapis.com/brain-genomics/awcarroll/share/giab/element/HG002.novaseq.pcr-free.50x.dedup.grch38.vcf.gz
    benchmark: HG002_asm_v27_XY
    variables:
      coverage: 50
      seqtech: Illumina PCR-Free
      variant_caller: DeepVariant
    corrections:
      fix_refcall_gt: true

  HG002_Ultima_DV:
    refset: GRCh38_XY
    chr_prefix: chr
    src:
      url: https://s3.amazonaws.com/ultima-selected-1k-genomes-vcf-only/DeepVariant_vcfs/HG002_005401-UGAv3-1-CACATCCTGCATGTGAT.vcf.gz
    benchmark: HG002_asm_v27_XY
    variables:
      coverage: 40
      seqtech: Ultima
      variant_caller: DeepVariant
    corrections:
      fix_refcall_gt: true


unlabeled_queries: {}

models:
  xy_fp:
    train: [HG002_Illumina_DV, HG002_Ultima_DV, HG002_Element_DV]

    vartypes: [SNV, INDEL]
    error_labels: [fp]
    filtered_are_candidates: true

    features:

      VAR_seqtech:
        feature_type: categorical
      VCF_VAF: {}
      VCF_DP:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 100}
      VCF_indel_length:
        visualization:
          truncate: {lower: -50, upper: 50}

      HOMOPOL_A_length: &homopol_length
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_T_length: *homopol_length
      HOMOPOL_G_length: *homopol_length
      HOMOPOL_C_length: *homopol_length
      HOMOPOL_A_imperfect_frac: &homopol_frac
        fill_na: -1
        visualization:
          split_missing: 0
      HOMOPOL_T_imperfect_frac: *homopol_frac
      HOMOPOL_G_imperfect_frac: *homopol_frac
      HOMOPOL_C_imperfect_frac: *homopol_frac

      TR_unit_size_max:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      TR_unit_copies_max:
        visualization:
          truncate: {lower: 0, upper: 50}
      TR_identity_min: {}
      TR_length:
        transform: log
        visualization:
          split_missing: 0
      TR_percent_AT_median:
        fill_na: -1
        visualization:
          split_missing: 0

      REPMASK_SINE_length:
        transform: binary
        alt_name: REPMASK_SINE
        feature_type: categorical
      REPMASK_LTR_length:
        transform: binary
        alt_name: REPMASK_LTR
        feature_type: categorical
      REPMASK_LINE_length: {}

      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      SEGDUP_size_max: {}
      SEGDUP_identity_mean: {}
      SEGDUP_count:
        visualization:
          plot_type: bar
          truncate: {upper: 50}

    interactions: 20

references:
  GRCh38:
    sdf:
      src:
        url: https://s3.amazonaws.com/rtg-datasets/references/GRCh38.sdf.zip
      chr_prefix: chr
      is_fasta: False
    strats:
      mhc: [{chrom: 6, start: 28510020, end: 33480577}]
    feature_data:
      mappability:
        low:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_lowmappabilityall.bed.gz
        high:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l250_m0_e0.bed.gz
      segdups:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
        params:
          bed_cols: {chrom: 1, start: 2, end: 3}
      tandem_repeats:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
        params:
          bed_cols: {chrom: 1, start: 2, end: 3}
      repeat_masker:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
        params:
          bed_cols: {chrom: 5, start: 6, end: 7}
        class_families:
          SINE: []
          LINE: [L1, L2, CR1, RTE-BovB, Dong-R4]
          LTR: []
          Satellite: []
    benchmarks:
      # from here: https://drive.google.com/drive/u/1/folders/1rkqRr1TnUiHFYsi12dkqqxEW2pfh7d4x
      HG002_asm_v27_XY:
        vcf:
          src: 
            filepath: data/benchmarks/GRCh38_T2T-XY-v2.7_dipcall-z2k.vcf.gz
            md5: 1a6a1c72e98559b658757c63d43d3355
        bed:
          src: 
            filepath: data/benchmarks/GRCh38_T2T-XY-v2.7_dipcall-z2k.excluded.bed.gz
            md5: 899ab59823159dd6d431579cabf43c34

feature_definitions:
  variables:
    continuous:
      coverage:
        lower: 1
    categorical:
      seqtech:
        levels: ["PacBio HiFi", "Illumina PCR-Free", "Element", "Ultima"]
        description: Sequencing tech used to produce the reads for the VCF file
      variant_caller:
        levels: ["DeepVariant"]
        description: Variant caller used to produce the VCF file
