reference_sets:
  GRCh38_auto:
    ref: GRCh38
    chr_filter: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

labeled_queries:
  HG003_ONT_old: &ont_old
    chr_prefix: chr
    corrections:
      fix_refcall_gt: true
    split_biallelics: true
    benchmark: HG003_v4
    refset: GRCh38_auto
    src:
      url: http://www.bio8.cs.hku.hk/clair3/analysis_result/ont_guppy4/2_coverage_subsampling/clair/hg003_40x_clair_filter_q748.vcf.gz
    variables:
      pipeline: clair1+guppy4

  HG003_ONT_new:
    <<: *ont_old
    src:
      url: http://www.bio8.cs.hku.hk/clair3/analysis_result/ont_guppy5/2_coverage_subsampling/clair3/hg003_40x_clair3.vcf.gz
    variables:
      pipeline: clair3+guppy5

models:
  ont_new_v_old_fn:
    train:
      - HG003_ONT_old
      - HG003_ONT_new

    test: {}

    vartypes: [SNV, INDEL]
    error_labels: [fn]
    filtered_are_candidates: false

    interactions: [VAR_pipeline]

    features: &feature_base

      VAR_pipeline:
        feature_type: categorical
        visualization:
          plot_type: bar

      VCF_indel_length:
        visualization:
          plot_type: bar
          truncate: {lower: -50, upper: 50}

      HOMOPOL_A_length: &homopol_length
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_T_length: *homopol_length
      HOMOPOL_G_length: *homopol_length
      HOMOPOL_C_length: *homopol_length
      HOMOPOL_A_imperfect_frac: &homopol_frac
        fill_na: -1
        visualization:
          split_missing: 0
      HOMOPOL_T_imperfect_frac: *homopol_frac
      HOMOPOL_G_imperfect_frac: *homopol_frac
      HOMOPOL_C_imperfect_frac: *homopol_frac

      TR_unit_size_max:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      TR_identity_min: {}
      TR_length:
        transform: log
        visualization:
          split_missing: 0
      TR_percent_AT_median:
        fill_na: -1
        visualization:
          split_missing: 0

      REPMASK_SINE_length:
        transform: binary
        alt_name: REPMASK_SINE
        feature_type: categorical
      REPMASK_LTR_length:
        transform: binary
        alt_name: REPMASK_LTR
        feature_type: categorical
      REPMASK_LINE_length: {}

      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      SEGDUP_size_max: {}
      SEGDUP_identity_mean: {}
      SEGDUP_count:
        visualization:
          plot_type: bar
          truncate: {upper: 50}

references:
  GRCh38:
    sdf:
      src:
        url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
      chr_prefix: chr
      is_fasta: true
    strats:
      mhc: [{chrom: 6, start: 28510020, end: 33480577}]
    feature_data:
      mappability:
        low:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_lowmappabilityall.bed.gz
        high:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l250_m0_e0.bed.gz
      segdups:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
        params:
          bed_cols: {chrom: 1, start: 2, end: 3}
      tandem_repeats:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
        params:
          bed_cols: {chrom: 1, start: 2, end: 3}
      repeat_masker:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
        params:
          bed_cols: {chrom: 5, start: 6, end: 7}
        class_families:
          SINE: []
          LINE: [L1, L2, CR1, RTE-BovB, Dong-R4]
          LTR: []
          Satellite: []
    benchmarks:
      HG003_v4:
        vcf:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG003_NA24149_father/NISTv4.2.1/GRCh38/HG003_GRCh38_1_22_v4.2.1_benchmark.vcf.gz
            md5: 3ee131b29185d128315cac54a6488a01
        bed:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG003_NA24149_father/NISTv4.2.1/GRCh38/HG003_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed
            md5: 26f7a0a353c653e4e2979654586110b1

feature_definitions:
  variables:
    categorical:
      pipeline:
        levels:
          - "clair1+guppy4"
          - "clair3+guppy5"
        description: Base/variant callers used to create the VCF
