reference_sets:
  GRCh38_auto:
    ref: GRCh38
    chr_filter: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

labeled_queries:
  HG002_Ultima_old: &ult_old
    chr_prefix: chr
    corrections:
      fix_refcall_gt: true
    split_biallelics: true
    benchmark: HG002_q100
    refset: GRCh38_auto
    src:
      url: https://s3.amazonaws.com/ultima-selected-1k-genomes-vcf-only/DeepVariant_vcfs/HG002_005401-UGAv3-1-CACATCCTGCATGTGAT.vcf.gz
    corrections:
      # bcftools complains about wrong number of fields for SB (strand bias) on some lines
      strip_format_fields: ["SB"]
    variables:
      seqtech: Ultima-old

  HG002_Ultima_new:
    <<: *ult_old
    src:
      url: https://giab-data.s3.amazonaws.com/ultima-GIAB-Feb-2024/DeepVariant_vcfs/NA24385-Z0027.annotated.AF.vcf.gz
    variables:
      seqtech: Ultima-new

  HG002_Ultima_v4:
    <<: *ult_old
    benchmark: HG002_v4
    src:
      url: https://s3.amazonaws.com/ultima-selected-1k-genomes-vcf-only/DeepVariant_vcfs/HG002_005401-UGAv3-1-CACATCCTGCATGTGAT.vcf.gz
  
  HG007_Ultima_v4:
    <<: *ult_old
    benchmark: HG007_v4
    src:
      url: https://s3.amazonaws.com/ultima-selected-1k-genomes-vcf-only/DeepVariant_vcfs/HG007_004731-UGAv3-33-CATGCAGCGCTAATGA.vcf.gz

models:
  ultima_old_v_new_fn:
    train:
      - HG002_Ultima_old
      - HG002_Ultima_new

    test:
      HG002:
        query_key: HG002_Ultima_v4
        variables:
          seqtech: Ultima-old
      HG007:
        query_key: HG007_Ultima_v4
        variables:
          seqtech: Ultima-old

    vartypes: [SNV, INDEL]
    error_labels: [fn]
    filtered_are_candidates: false

    interactions: [VAR_seqtech]

    features: &feature_base

      VAR_seqtech:
        feature_type: categorical
        visualization:
          plot_type: bar

      VCF_indel_length:
        visualization:
          plot_type: bar
          truncate: {lower: -50, upper: 50}

      HOMOPOL_A_length: &homopol_length
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      HOMOPOL_T_length: *homopol_length
      HOMOPOL_G_length: *homopol_length
      HOMOPOL_C_length: *homopol_length
      HOMOPOL_A_imperfect_frac: &homopol_frac
        fill_na: -1
        visualization:
          split_missing: 0
      HOMOPOL_T_imperfect_frac: *homopol_frac
      HOMOPOL_G_imperfect_frac: *homopol_frac
      HOMOPOL_C_imperfect_frac: *homopol_frac

      TR_unit_size_max:
        visualization:
          plot_type: bar
          truncate: {lower: 0, upper: 50}
      TR_identity_min: {}
      TR_length:
        transform: log
        visualization:
          split_missing: 0
      TR_percent_AT_median:
        fill_na: -1
        visualization:
          split_missing: 0

      REPMASK_SINE_length:
        transform: binary
        alt_name: REPMASK_SINE
        feature_type: categorical
      REPMASK_LTR_length:
        transform: binary
        alt_name: REPMASK_LTR
        feature_type: categorical
      REPMASK_LINE_length: {}

      MAP_difficult_250bp:
        feature_type: categorical
      MAP_difficult_100bp:
        feature_type: categorical

      SEGDUP_size_max: {}
      SEGDUP_identity_mean: {}
      SEGDUP_count:
        visualization:
          plot_type: bar
          truncate: {upper: 50}

references:
  GRCh38:
    sdf:
      src:
        url: https://s3.amazonaws.com/rtg-datasets/references/GRCh38.sdf.zip
      chr_prefix: chr
      is_fasta: False
    strats:
      mhc: [{chrom: 6, start: 28510020, end: 33480577}]
    feature_data:
      mappability:
        low:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_lowmappabilityall.bed.gz
        high:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v3.0/GRCh38/mappability/GRCh38_nonunique_l250_m0_e0.bed.gz
      segdups:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
        params:
          bed_cols: {chrom: 1, start: 2, end: 3}
      tandem_repeats:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
        params:
          bed_cols: {chrom: 1, start: 2, end: 3}
      repeat_masker:
        src:
          url: https://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
        params:
          bed_cols: {chrom: 5, start: 6, end: 7}
        class_families:
          SINE: []
          LINE: [L1, L2, CR1, RTE-BovB, Dong-R4]
          LTR: []
          Satellite: []
    benchmarks:
      HG002_v4:
        vcf:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz
            md5: dc750b3807d4af1f7ffec852e9c2f771
        bed:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/NISTv4.2.1/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed
            md5: 7a3acc9f7e2ab5daa9fd4d42919aa4c6

      HG007_v4:
        vcf:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG007_NA24695_mother/NISTv4.2.1/GRCh38/HG007_GRCh38_1_22_v4.2.1_benchmark.vcf.gz
            md5: 336f8cf6806521618779b6c5f4eadeb7
        bed:
          src:
            url: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG007_NA24695_mother/NISTv4.2.1/GRCh38/HG007_GRCh38_1_22_v4.2.1_benchmark.bed
            md5: e09338dd438f89bb889ab9ed6b3a1b3a

      # from here: https://drive.google.com/drive/u/1/folders/1FNcfcup7_vEBBmrRFN9ZPMOV540joUZm
      HG002_q100:
        vcf:
          src: 
            filepath: data/benchmarks/GRCh38_HG2-T2TQ100-V0.9_dipcall-z2k.vcf.gz
            md5: 054de8d804f2eb42ff17ff21d3694c16
        bed:
          src: 
            filepath: data/benchmarks/GRCh38_HG2-T2TQ100-V0.9_dipcall-z2k.benchmark.bed.gz
            md5: 972bd257859de5c58773567087c22411

feature_definitions:
  variables:
    categorical:
      seqtech:
        levels:
          - "Ultima-old"
          - "Ultima-new"
        description: Ultima version used for generating sequence
